# Generated by Django 2.1.1 on 2018-11-25 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20181121_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('bio', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='Posts/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
