# Generated by Django 2.1.1 on 2018-11-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20181125_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=250),
        ),
    ]
