# Generated by Django 2.1.1 on 2018-11-26 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20181126_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default=datetime.datetime(2018, 11, 26, 6, 23, 24, 489568, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
